name: Auto Update Remote Files

on:
  schedule:
    - cron: '30 0,12 * * *'
      timezone: 'Asia/Shanghai'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download
        run: |
          # 格式: 相对仓库根目录的文件路径|URL
          LISTS=(


            # 广告拉取
            "geo/geosite/Tracking.mrs|https://github.com/666OS/rules/raw/release/mihomo/domain/Tracking.mrs"
            "geo/geosite/Tracking.txt|https://github.com/666OS/rules/raw/release/mihomo/domain/Tracking.txt"
            
            "geo/geosite/adblock.mrs|https://github.com/217heidai/adblockfilters/raw/main/rules/adblockmihomo.mrs"
            "geo/geosite/adblock.yaml|https://github.com/217heidai/adblockfilters/raw/main/rules/adblockmihomo.yaml"

            "geo/geosite/adblocklite.mrs|https://github.com/217heidai/adblockfilters/raw/main/rules/adblockmihomolite.mrs"
            "geo/geosite/adblocklite.yaml|https://github.com/217heidai/adblockfilters/raw/main/rules/adblockmihomolite.yaml"
            
            "geo/geosite/category-ads-all.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ads-all.mrs"
            "geo/geosite/category-ads-all.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ads-all.list"

            "geo/geosite/AWAvenue-Ads-Rule-Clash.mrs|https://github.com/TG-Twilight/AWAvenue-Ads-Rule/raw/main/Filters/AWAvenue-Ads-Rule-Clash.mrs"
            "geo/geosite/AWAvenue-Ads-Rule-Clash.yaml|https://github.com/TG-Twilight/AWAvenue-Ads-Rule/raw/main/Filters/AWAvenue-Ads-Rule-Clash.yaml"

            "geo/geosite/anti-ad-clash.yaml|https://github.com/privacy-protection-tools/anti-AD/raw/master/anti-ad-clash.yaml"

            # fakeip-filter拉取
            "geo/geosite/fakeip-filter.mrs|https://github.com/DustinWin/ruleset_geodata/raw/mihomo-ruleset/fakeip-filter.mrs"
            "geo/geosite/fakeip-filter.list|https://github.com/DustinWin/ruleset_geodata/raw/mihomo-ruleset/fakeip-filter.list"

            "geo/geosite/Direct.mrs|https://github.com/666OS/rules/raw/release/mihomo/domain/Direct.mrs"
            "geo/geosite/Direct.txt|https://github.com/666OS/rules/raw/release/mihomo/domain/Direct.txt"

            "rule/fakeip_filter_cn.list|https://github.com/qichiyuhub/rule/blob/main/rules/fakeipfilter-cn.list"
            "rule/fakeip_filter_!cn.list|https://github.com/qichiyuhub/rule/blob/main/rules/fakeipfilter-!cn.list"
            
           # Aethersailor规则拉取
            "rule/Custom_Direct_Domain.mrs|https://github.com/Aethersailor/Custom_OpenClash_Rules/raw/main/rule/Custom_Direct_Domain.mrs"
            "rule/Custom_Direct_Domain.yaml|https://github.com/Aethersailor/Custom_OpenClash_Rules/raw/main/rule/Custom_Direct_Domain.yaml"

            "rule/Custom_Direct_IP.mrs|https://github.com/Aethersailor/Custom_OpenClash_Rules/raw/main/rule/Custom_Direct_IP.mrs"
            "rule/Custom_Direct_IP.yaml|https://github.com/Aethersailor/Custom_OpenClash_Rules/raw/main/rule/Custom_Direct_IP.yaml"

            "rule/Custom_Direct_Classical_Port.yaml|https://github.com/Aethersailor/Custom_OpenClash_Rules/raw/main/rule/Custom_Direct_Classical_Port.yaml"

            "rule/Custom_Port_Direct.yaml|https://github.com/Aethersailor/Custom_OpenClash_Rules/raw/main/rule/Custom_Port_Direct.yaml"

            "rule/Custom_Proxy_Domain.mrs|https://github.com/Aethersailor/Custom_OpenClash_Rules/raw/main/rule/Custom_Proxy_Domain.mrs"
            "rule/Custom_Proxy_Domain.yaml|https://github.com/Aethersailor/Custom_OpenClash_Rules/raw/main/rule/Custom_Proxy_Domain.yaml"

            "rule/Custom_Proxy_IP.mrs|https://github.com/Aethersailor/Custom_OpenClash_Rules/raw/main/rule/Custom_Proxy_IP.mrs"
            "rule/Custom_Proxy_IP.yaml|https://github.com/Aethersailor/Custom_OpenClash_Rules/raw/main/rule/Custom_Proxy_IP.yaml"

            "rule/Steam_CDN_Domain.mrs|https://github.com/Aethersailor/Custom_OpenClash_Rules/raw/main/rule/Steam_CDN_Domain.mrs"
            "rule/Steam_CDN_Domain.yaml|https://github.com/Aethersailor/Custom_OpenClash_Rules/raw/main/rule/Steam_CDN_Domain.yaml"

            "rule/Steam_CDN_IP.mrs|https://github.com/Aethersailor/Custom_OpenClash_Rules/raw/main/rule/Steam_CDN_IP.mrs"
            "rule/Steam_CDN_IP.yaml|https://github.com/Aethersailor/Custom_OpenClash_Rules/raw/main/rule/Steam_CDN_IP.yaml"

           # MetaCubeX规则拉取
            "geo/geosite/private.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/private.mrs"
            "geo/geosite/private.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/private.list"

            "geo/geosite/docker.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/docker.mrs"
            "geo/geosite/docker.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/docker.list"

            "geo/geosite/google-cn.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google-cn.mrs"
            "geo/geosite/google-cn.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google-cn.list"

            "geo/geosite/category-games@cn.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-games@cn.mrs"
            "geo/geosite/category-games@cn.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-games@cn.list"

            "geo/geosite/category-game-platforms-download.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-game-platforms-download.mrs"
            "geo/geosite/category-game-platforms-download.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-game-platforms-download.list"

            "geo/geosite/category-public-tracker.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-public-tracker.mrs"
            "geo/geosite/category-public-tracker.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-public-tracker.list"

            "geo/geosite/category-pt.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-pt.mrs"
            "geo/geosite/category-pt.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-pt.list"

            "geo/geosite/category-communication.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-communication.mrs"
            "geo/geosite/category-communication.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-communication.list"

            "geo/geosite/category-social-media-!cn.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-social-media-!cn.mrs"
            "geo/geosite/category-social-media-!cn.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-social-media-!cn.list"

            "geo/geosite/anthropic.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/anthropic.mrs"
            "geo/geosite/anthropic.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/anthropic.list"

            "geo/geosite/google-gemini.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google-gemini.mrs"
            "geo/geosite/google-gemini.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google-gemini.list"

            "geo/geosite/openai.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/openai.mrs"
            "geo/geosite/openai.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/openai.list"

            "geo/geosite/x.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/x.mrs"
            "geo/geosite/x.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/x.list"

            "geo/geosite/category-ai-!cn.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-!cn.mrs"
            "geo/geosite/category-ai-!cn.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-!cn.list"

            "geo/geosite/github.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/github.mrs"
            "geo/geosite/github.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/github.list"

            "geo/geosite/speedtest.mrs|https://github.com/666OS/rules/raw/release/mihomo/domain/Speedtest.mrs"
            "geo/geosite/speedtest.txt|https://github.com/666OS/rules/raw/release/mihomo/domain/Speedtest.txt"

            "geo/geosite/category-speedtest.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-speedtest.mrs"
            "geo/geosite/category-speedtest.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-speedtest.list"

            "geo/geosite/test-ipv6.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/test-ipv6.mrs"
            "geo/geosite/test-ipv6.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/test-ipv6.list"

            "geo/geosite/youtube.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/youtube.mrs"
            "geo/geosite/youtube.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/youtube.list"

            "geo/geosite/apple-tvplus.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple-tvplus.mrs"
            "geo/geosite/apple-tvplus.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple-tvplus.list"

            "geo/geosite/apple-cn.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple-cn.mrs"
            "geo/geosite/apple-cn.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple-cn.list"
 
            "geo/geosite/apple@cn.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple@cn.mrs"
            "geo/geosite/apple@cn.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple@cn.list"

            "geo/geosite/apple.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple.mrs"
            "geo/geosite/apple.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple.list"

            "geo/geosite/onedrive.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/onedrive.mrs"
            "geo/geosite/onedrive.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/onedrive.list"

            "geo/geosite/bing@cn.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/bing@cn.mrs"
            "geo/geosite/bing@cn.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/bing@cn.list"

            "geo/geosite/bing.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/bing.mrs"
            "geo/geosite/bing.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/bing.list"

            "geo/geosite/microsoft@cn.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft@cn.mrs"
            "geo/geosite/microsoft@cn.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft@cn.list"

            "geo/geosite/microsoft.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft.mrs"
            "geo/geosite/microsoft.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft.list"

            "geo/geosite/googlefcm.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/googlefcm.mrs"
            "geo/geosite/googlefcm.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/googlefcm.list"

            "geo/geosite/google.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google.mrs"
            "geo/geosite/google.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google.list"

            "geo/geosite/tiktok.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tiktok.mrs"
            "geo/geosite/tiktok.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tiktok.list"

            "geo/geosite/netflix.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/netflix.mrs"
            "geo/geosite/netflix.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/netflix.list"

            "geo/geosite/disney.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/disney.mrs"
            "geo/geosite/disney.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/disney.list"

            "geo/geosite/hbo.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/hbo.mrs"
            "geo/geosite/hbo.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/hbo.list"

            "geo/geosite/primevideo.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/primevideo.mrs"
            "geo/geosite/primevideo.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/primevideo.list"

            "geo/geosite/category-emby.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-emby.mrs"
            "geo/geosite/category-emby.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-emby.list"

            "geo/geosite/spotify.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/spotify.mrs"
            "geo/geosite/spotify.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/spotify.list"

            "geo/geosite/bahamut.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/bahamut.mrs"
            "geo/geosite/bahamut.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/bahamut.list"

            "geo/geosite/steam.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/steam.mrs"
            "geo/geosite/steam.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/steam.list"

            "geo/geosite/category-games-cn.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-games-cn.mrs"
            "geo/geosite/category-games-cn.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-games-cn.list"

            "geo/geosite/category-games.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-games.mrs"
            "geo/geosite/category-games.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-games.list"

            "geo/geosite/category-entertainment.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-entertainment.mrs"
            "geo/geosite/category-entertainment.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-entertainment.list"

            "geo/geosite/category-ecommerce.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ecommerce.mrs"
            "geo/geosite/category-ecommerce.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ecommerce.list"

            "geo/geosite/category-cryptocurrency.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-cryptocurrency.mrs"
            "geo/geosite/category-cryptocurrency.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-cryptocurrency.list"

            "geo/geosite/gfw.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/gfw.mrs"
            "geo/geosite/gfw.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/gfw.list"

            "geo/geosite/geolocation-!cn.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/geolocation-!cn.mrs"
            "geo/geosite/geolocation-!cn.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/geolocation-!cn.list"

            "geo/geosite/geolocation-cn.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/geolocation-cn.mrs"
            "geo/geosite/geolocation-cn.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/geolocation-cn.list"

            "geo/geosite/cn.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/cn.mrs"
            "geo/geosite/cn.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/cn.list"

            "geo/geoip/private.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/private.mrs"
            "geo/geoip/private.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/private.list"

            "geo/geoip/telegram.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/telegram.mrs"
            "geo/geoip/telegram.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/telegram.list"

            "geo/geoip/twitter.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/twitter.mrs"
            "geo/geoip/twitter.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/twitter.list"

            "geo/geoip/facebook.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/facebook.mrs"
            "geo/geoip/facebook.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/facebook.list"

            "geo/geoip/google.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/google.mrs"
            "geo/geoip/google.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/google.list"

            "geo/geoip/netflix.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/netflix.mrs"
            "geo/geoip/netflix.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/netflix.list"

            "geo/geoip/cloudflare.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cloudflare.mrs"
            "geo/geoip/cloudflare.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cloudflare.list"

            "geo/geoip/cloudfront.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cloudfront.mrs"
            "geo/geoip/cloudfront.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cloudfront.list"

            "geo/geoip/fastly.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/fastly.mrs"
            "geo/geoip/fastly.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/fastly.list"

            "geo/geoip/cn.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cn.mrs"
            "geo/geoip/cn.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cn.list"

            "geo/geosite/wikimedia.mrs|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/wikimedia.mrs"
            "geo/geosite/wikimedia.list|https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/wikimedia.list"

            
          )

          for jntm in "${LISTS[@]}"; do
            IFS="|" read -r filepath url <<< "$jntm"
            echo "Processing $filepath..."
            
            # 获取文件所在的父目录路径
            filedir=$(dirname "$filepath")
            
            # 如果目录不存在，则递归创建该目录
            if [ "$filedir" != "." ]; then
              mkdir -p "$filedir"
            fi

            # 下载文件到指定位置
            curl -sfL "$url" -o "$filepath" || echo "Failed to download $filepath"
          done

      - name: global config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: commit
        id: commit
        run: |
          # 暂存当前目录下所有发生变化的文件（包括新创建的多级目录和文件）
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "auto update rules $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
